# Generated by Django 2.2.5 on 2019-09-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('discordid', models.BigIntegerField()),
                ('url', models.TextField()),
            ],
        ),
    ]
