# Generated by Django 3.0 on 2019-12-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Client',
        ),
    ]
