# Generated by Django 3.0.1 on 2019-12-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='arme',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
