# Generated by Django 3.0 on 2019-12-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0002_auto_20191204_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='discordid',
        ),
        migrations.RemoveField(
            model_name='client',
            name='url',
        ),
    ]
