# Generated by Django 3.0.1 on 2019-12-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0004_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
