# Generated by Django 3.0.1 on 2019-12-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0005_auto_20191223_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
