# Generated by Django 3.0.1 on 2019-12-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
