# Generated by Django 3.0.1 on 2019-12-23 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('siteweb', '0008_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristiques',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('attaque', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('vitesse', models.IntegerField()),
                ('precision', models.IntegerField()),
                ('effet', models.IntegerField()),
            ],
        ),
    ]
