# Generated by Django 3.0.1 on 2019-12-23 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteweb', '0009_caracteristiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristiques',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
