# Generated by Django 3.0.1 on 2019-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0010_auto_20191223_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristiques',
            name='niveau',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
